import { brandGreen } from "@/components/app-providers";
import { StyleSheet } from "react-native";

export const $styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#1a1f2e',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 16,
    maxHeight: '90%',
    minHeight: '60%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2f3e',
  },
  modalTitle: {
    color: 'white',
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  qrContainer: {
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 24,
  },
  actionButtons: {
    paddingHorizontal: 24,
    gap: 16,
    marginBottom: 8,
  },
  actionButton: {
    backgroundColor: '#252a3a',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#2a2f3e',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  actionButtonContent: {
    alignItems: 'center',
  },
  actionButtonIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(50, 213, 131, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  actionButtonIcon: {
    fontSize: 24,
  },
  actionButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
    textAlign: 'center',
  },
  actionButtonSubtext: {
    color: '#9CA1AB',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  instructionsContainer: {
    margin: 24,
    backgroundColor: '#252a3a',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#2a2f3e',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  instructionsTitle: {
    color: 'white',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
    textAlign: 'center',
  },
  instructionsSubtitle: {
    color: brandGreen,
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 20,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  instructionStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    paddingRight: 8,
  },
  stepNumber: {
    color: 'white',
    fontSize: 14,
    fontWeight: '700',
    width: 32,
    height: 32,
    textAlign: 'center',
    backgroundColor: brandGreen,
    borderRadius: 16,
    lineHeight: 32,
    marginRight: 16,
    shadowColor: brandGreen,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  stepText: {
    color: '#DADADA',
    fontSize: 14,
    flex: 1,
    lineHeight: 22,
  },
  codeContainer: {
    marginTop: 20,
  },
  codeLabel: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  codeBox: {
    backgroundColor: '#1a1f2e',
    borderRadius: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: brandGreen,
    shadowColor: brandGreen,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  codeText: {
    color: brandGreen,
    fontSize: 12,
    fontFamily: 'monospace',
    lineHeight: 18,
    textAlign: 'center',
  },
  codeHelper: {
    color: '#9CA1AB',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  manualActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  manualButton: {
    flex: 1,
    backgroundColor: brandGreen,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    shadowColor: brandGreen,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  manualButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  webNotice: {
    margin: 24,
    marginBottom: 16,
    backgroundColor: 'rgba(50, 213, 131, 0.1)',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(50, 213, 131, 0.3)',
    alignItems: 'center',
  },
  webNoticeIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  webNoticeTitle: {
    color: brandGreen,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  webNoticeText: {
    color: '#DADADA',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
  primaryActionButton: {
    backgroundColor: 'rgba(50, 213, 131, 0.1)',
    borderColor: brandGreen,
    borderWidth: 1,
  },
  primaryIconContainer: {
    backgroundColor: 'rgba(50, 213, 131, 0.2)',
  },
  primaryActionText: {
    color: brandGreen,
  },
});
